### ISSUE TITLE
problem with fallback set to error

### ISSUE THREAD

**Issue by ksdavidc** [GnoxNahte/obsidian-auto-embed#8]
I am still trying to figure out what is going on so this is incomplete. Putting it here in case anyone else is encountering something similar.

If I set fallback to show error, I get the following message, and notes becomes unreadable unnagivable.

[auto embed.log](https://github.com/user-attachments/files/17006361/auto.embed.log)

Using latest obsidian on mac with sonoma.

```
plugin:auto-embed:405 Uncaught TypeError: Cannot read properties of null (reading 'dataset')
    at DefaultFallbackEmbed.create (plugin:auto-embed:405:16)
    at EmbedWidget.toDOM (plugin:auto-embed:355:52)
    at t.sync (app.js:1:322514)
    at e.sync (app.js:1:313021)
    at t.sync (app.js:1:329284)
    at e.sync (app.js:1:313021)
    at app.js:1:354351
    at e.ignore (app.js:1:434969)
    at t.updateInner (app.js:1:354133)
    at t.update (app.js:1:353888)
    at e.update (app.js:1:443717)
    at e.dispatchTransactions (app.js:1:440278)
    at e.dispatch (app.js:1:442266)
    at app.js:1:1608575
```

embed works if I choose embed as fallback.

Seems perhaps linked to floating toc plugin, but still figure it out....

**Comment by GnoxNahte** [comment]
Thanks for the bug report! It was a mistake on my part, it should be fixed in the next update! Let me know if you find any other bugs.
